### ISSUE TITLE
Append Number In Case of Name Collision

### ISSUE THREAD

**Issue by alivefromupstairs** [subdownloader/subdownloader#47]
**Problem:**
Name collision:
![image](https://user-images.githubusercontent.com/46059092/69916284-8721b700-1459-11ea-90a5-61c9eb937dce.png)

**Solution:**
Append `.num` to the file name. `naked.lunch.1991.eng.srt` => `naked.lunch.1991.eng.1.srt` & ` naked.lunch.1991.eng.2.srt` 

It works with `mpv` and `vlc` with `srt` files. I have not tested other formats and video players.

```yml 
  SubDownloader Version: 2.1.0
  Python Version: 3.7.4
  Operating System: Arch Linux
```
